apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: v0.21.0
  name: devlake-grafana
  namespace: devlake
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    app.kubernetes.io/version: v0.21.0
  name: devlake-lake
  namespace: devlake
spec:
  ports:
  - name: devlake
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    devlakeComponent: lake
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    app.kubernetes.io/version: v0.21.0
  name: devlake-mysql
  namespace: devlake
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    devlakeComponent: mysql
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    app.kubernetes.io/version: v0.21.0
  name: devlake-ui
  namespace: devlake
spec:
  ports:
  - name: ui
    nodePort: 30007
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: devlake
    devlakeComponent: ui
  sessionAffinity: None
  type: NodePort
