apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devlake-lake
  namespace: devlake
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devlake
  namespace: devlake
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
