apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: v0.21.0
  name: devlake-grafana
  namespace: devlake
