apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    root_url = %(protocol)s://%(domain)s/grafana
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: devlake
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: v0.21.0
  name: devlake-grafana
  namespace: devlake

---
apiVersion: v1
data:
  ENCRYPTION_SECRET: YDYGKEYKLLCTYYFVSNHBNKQLOUTVKUAMDSDTIMYOPPPBEFVMJWPHWGMWASBAGIQCDZEYASVJKRDXXWCELBEDFNPHMLMSTKBOYJMGPJFRGPOXQFQHLGKZNGMKVQRHPWCF
kind: ConfigMap
metadata:
  name: devlake-lake
  namespace: devlake
