apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana
  namespace: devlake
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/hostpath-provisioner/default/devlake-grafana
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: devlake-lake
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-devlake-mysql
  namespace: devlake
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 55Gi
  hostPath:
    path: /tmp/hostpath-provisioner/default/devlake-mysql-data-devlake-mysql-0
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
